package fragrant.generator;

public enum StructureType {
    ANCIENT_CITY,
    BASTION_REMNANT,
    BURIED_TREASURE,
    DESERT_TEMPLE,
    END_CITY,
    IGLOO,
    JUNGLE_TEMPLE,
    MINESHAFT,
    NETHER_FORTRESS,
    OCEAN_RUIN,
    OCEAN_MONUMENT,
    PILLAGER_OUTPOST,
    RUINED_PORTAL_N,
    RUINED_PORTAL_O,
    SHIPWRECK,
    STRONGHOLD,
    TRAIL_RUINS,
    TRIAL_CHAMBERS,
    VILLAGE,
    WITCH_HUT,
    WOODLAND_MANSION
}
